"""
Django settings for UniRV_Django project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import shutil
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# Em desenvolvimento, padrão é True. Em produção, definir DJANGO_DEBUG=False explicitamente
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# Detect if we're running tests
# Django sets sys.argv[1] to 'test' when running tests
# Also check for 'pytest' or 'unittest' in command line
TESTING = (
    len(sys.argv) > 1 and (
        sys.argv[1] == 'test' or 
        'pytest' in sys.argv[0] or 
        'unittest' in sys.argv[0] or
        'test' in sys.argv
    )
)

# Security: explicit ALLOWED_HOSTS
# Parsear e validar ALLOWED_HOSTS antes de usar
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '').strip()
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    # Em produção, usar variável de ambiente
    # Em desenvolvimento sem DEBUG, ainda permitir localhost
    if allowed_hosts_env:
        # Parsear hosts e filtrar valores vazios
        parsed_hosts = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
        # Validar que há pelo menos um host válido
        if parsed_hosts:
            ALLOWED_HOSTS = parsed_hosts
        else:
            # Se parsing resultou em lista vazia, usar fallback para desenvolvimento
            ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
    else:
        # Fallback para desenvolvimento: permitir localhost mesmo sem DEBUG
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # For timesince and other human-readable filters
    'tailwind',
    'theme',  # Tailwind theme app
    'editais.apps.EditaisConfig',
]

# Check if compressor is available (optional dependency)
# This check is done once and reused throughout settings
HAS_COMPRESSOR = False
try:
    import compressor
    HAS_COMPRESSOR = True
    INSTALLED_APPS.insert(-1, 'compressor')  # Insert before editais app
except ImportError:
    # Compressor not installed, skip it
    pass

# Add django_browser_reload only in DEBUG mode and not during testing
# TESTING mode disables django_browser_reload to avoid namespace issues in test environment
if DEBUG and not TESTING:
    INSTALLED_APPS += ['django_browser_reload']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Add gzip compression for HTML responses
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add django_browser_reload middleware only in DEBUG mode and not during testing
# Should be after any middleware that encodes the response (like GZipMiddleware)
if DEBUG and not TESTING:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

ROOT_URLCONF = 'UniRV_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UniRV_Django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tailwind CSS configuration
TAILWIND_APP_NAME = 'theme'

# NPM binary path (auto-detected with overrides for portability)
NPM_BIN_PATH = (
    os.environ.get('NPM_BIN_PATH')
    or shutil.which('npm')
    or shutil.which('npm.cmd')
    or 'npm'
)

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Add compressor finder if compressor is installed
if HAS_COMPRESSOR:
    STATICFILES_FINDERS.append('compressor.finders.CompressorFinder')

# Django Compressor settings for minification (only if compressor is installed)
if HAS_COMPRESSOR:
    # Compressor root and URL (defaults to STATIC_ROOT and STATIC_URL if not set)
    COMPRESS_ROOT = STATIC_ROOT
    # COMPRESS_URL should match the format used by {% static %} tag (with leading slash)
    COMPRESS_URL = '/static/' if not STATIC_URL.startswith('/') else STATIC_URL
    
    # Enable compression for Lighthouse testing even in DEBUG mode
    # Set COMPRESS_ENABLED=true environment variable to enable compression in development
    compress_enabled_env = os.environ.get('COMPRESS_ENABLED', '').lower() == 'true'
    if TESTING:
        COMPRESS_ENABLED = False
        COMPRESS_OFFLINE = False
    elif compress_enabled_env or not DEBUG:
        # Enable compression if explicitly requested or in production
        COMPRESS_ENABLED = True
        COMPRESS_OFFLINE = True
    else:
        # Default: disable in development to avoid file not found errors
        # But allow runtime compression (not offline) for testing
        COMPRESS_ENABLED = True  # Enable runtime compression
        COMPRESS_OFFLINE = False  # Don't require offline compression in dev
    
    COMPRESS_CSS_FILTERS = [
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.rCSSMinFilter',
    ]
    COMPRESS_JS_FILTERS = [
        'compressor.filters.jsmin.JSMinFilter',
    ]
else:
    # Compressor not installed, disable compression
    COMPRESS_ENABLED = False
    COMPRESS_OFFLINE = False

# WhiteNoise: serve compressed static files
# Use non-manifest storage during tests to avoid requiring collected static files
if TESTING:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Static files caching headers
# Set cache headers for both development and production
# Development: 1 hour cache for testing, Production: 1 year
# For Lighthouse testing, use longer cache even in development
# Note: CompressedManifestStaticFilesStorage automatically adds cache headers
# To test with longer cache in development, set: WHITENOISE_MAX_AGE=31536000
if DEBUG:
    # Allow override via environment variable for Lighthouse testing
    whitenoise_max_age_env = os.environ.get('WHITENOISE_MAX_AGE', '')
    if whitenoise_max_age_env:
        WHITENOISE_MAX_AGE = int(whitenoise_max_age_env)
    else:
        WHITENOISE_MAX_AGE = 3600  # 1 hour in seconds for development
else:
    WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds for production

# WhiteNoise compression settings
WHITENOISE_USE_FINDERS = True  # Use staticfiles finders for better performance
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in development mode
WHITENOISE_MANIFEST_STRICT = False  # Don't fail if manifest file is missing (useful in dev)

# Cache configuration
# Try Redis first, fallback to LocMemCache for development
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Use Redis in production if available
if not DEBUG:
    redis_host = os.environ.get('REDIS_HOST', '')
    redis_port = os.environ.get('REDIS_PORT', '6379')
    if redis_host:
        try:
            # Try django-redis first (recommended)
            import django_redis
            CACHES = {
                'default': {
                    'BACKEND': 'django_redis.cache.RedisCache',
                    'LOCATION': f'redis://{redis_host}:{redis_port}/1',
                    'OPTIONS': {
                        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    },
                    'KEY_PREFIX': 'unirv_editais',
                    'TIMEOUT': 300,  # Default timeout 5 minutes
                }
            }
        except ImportError:
            try:
                # Fallback to Django's built-in Redis backend (no CLIENT_CLASS option)
                import redis
                CACHES = {
                    'default': {
                        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                        'LOCATION': f'redis://{redis_host}:{redis_port}/1',
                        'KEY_PREFIX': 'unirv_editais',
                        'TIMEOUT': 300,  # Default timeout 5 minutes
                    }
                }
            except ImportError:
                # Redis not installed, use LocMemCache
                pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL for @login_required decorator
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/home/'

# Application-specific settings
EDITAIS_PER_PAGE = 12  # Number of editais to display per page
EDITAIS_CACHE_TTL = 300  # Cache TTL for index pages (5 minutes in seconds)
EDITAL_SEARCH_FIELDS = [
    'titulo', 'entidade_principal', 'numero_edital',
    'analise', 'objetivo', 'etapas', 'recursos',
    'itens_financiaveis', 'criterios_elegibilidade',
    'criterios_avaliacao', 'itens_essenciais_observacoes',
    'detalhes_unirv'
]

# Security settings for production
# Verificar se estamos em produção (DEBUG=False E ALLOWED_HOSTS válido e não-vazio)
# Alinhar com a validação do ALLOWED_HOSTS para evitar ativar segurança de produção
# com configuração inválida (ex: ALLOWED_HOSTS=' ' ou ALLOWED_HOSTS=',,,')
allowed_hosts_env_raw = os.environ.get('ALLOWED_HOSTS', '').strip()
has_valid_allowed_hosts = (
    allowed_hosts_env_raw and
    len([host.strip() for host in allowed_hosts_env_raw.split(',') if host.strip()]) > 0
)
is_production = not DEBUG and has_valid_allowed_hosts

if is_production:
    # Session security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    # Development: disable security features that require HTTPS
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    # Desabilitar HSTS completamente em desenvolvimento
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Session security settings (apply to both dev and production)
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire when browser closes
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Email configuration
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Console backend for development
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@agrohub.unirv.edu.br')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Site URL for email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Logging configuration (FEAT-013)
# Default to console logging; optional file handlers enabled via env vars
LOG_TO_FILE = os.environ.get('DJANGO_LOG_TO_FILE', '').lower() == 'true'
LOG_DIR = Path(os.environ.get('DJANGO_LOG_DIR', BASE_DIR / 'logs'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'structured': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'editais': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

if LOG_TO_FILE:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOGGING['handlers'].update({
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'performance_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'performance.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    })
    LOGGING['loggers']['django']['handlers'].append('file')
    LOGGING['loggers']['editais']['handlers'].append('file')
    LOGGING['loggers']['django.security']['handlers'] = ['security_file', 'console']
    LOGGING['loggers']['django.db.backends']['handlers'] = (
        ['performance_file'] if not DEBUG else ['console']
    )
