# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edital', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('entidade_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('em_andamento', 'Em Andamento')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('objetivo', models.TextField(blank=True)),
                ('etapas', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('itens_financiaveis', models.TextField(blank=True)),
                ('criterios_elegibilidade', models.TextField(blank=True)),
                ('criterios_avaliacao', models.TextField(blank=True)),
                ('itens_essenciais_observacoes', models.TextField(blank=True)),
                ('detalhes_unirv', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='editais.edital')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EditalValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moeda', models.CharField(default='BRL', max_length=10)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='editais.edital')),
            ],
        ),
    ]
