# Generated by Django 5.2.7 on 2025-11-04 21:33
#
# This migration adds user tracking and admin improvements:
# - Adds verbose names for better admin interface display
# - Adds created_by/updated_by fields to track who created/updated each edital
#   (uses SET_NULL to preserve data if user is deleted)
# - Creates EditalFavorite model (temporary feature - removed in migration 0007)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_edital_analise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['-data_atualizacao'], 'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AddField(
            model_name='edital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_editais', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='edital',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_editais', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        # Note: EditalFavorite was a temporary feature that was later removed
        # in migration 0007 when it was replaced by EditalHistory.
        # The migration history is preserved for reference.
        migrations.CreateModel(
            name='EditalFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='editais.edital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_editais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'edital')},
            },
        ),
    ]
