# Generated by Django 5.2.7 on 2025-11-05 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('editais', '0003_alter_cronograma_options_alter_edital_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['-data_atualizacao'], name='idx_data_atualizacao'),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['entidade_principal'], name='idx_entidade'),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['numero_edital'], name='idx_numero'),
        ),
    ]
