# Generated by Django 5.2.7 on 2025-11-12 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0004_edital_idx_data_atualizacao_edital_idx_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='edital',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('fechado', 'Fechado'), ('programado', 'Programado')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['slug'], name='idx_slug'),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='idx_status_dates'),
        ),
        migrations.AddIndex(
            model_name='edital',
            index=models.Index(fields=['titulo'], name='idx_titulo'),
        ),
    ]
