# Generated by Django 5.2.7 on 2025-11-12 01:06

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing Edital instances"""
    Edital = apps.get_model('editais', 'Edital')
    
    for edital in Edital.objects.filter(slug__isnull=True):
        base_slug = slugify(edital.titulo)
        slug = base_slug
        counter = 1
        
        # Ensure uniqueness
        while Edital.objects.filter(slug=slug).exclude(pk=edital.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        edital.slug = slug
        edital.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - set slugs to None"""
    Edital = apps.get_model('editais', 'Edital')
    Edital.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0005_add_slug_and_dates'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
