# Generated by Django 5.2.7 on 2025-11-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0006_populate_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Excluído')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.JSONField(blank=True, default=dict)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='editais.edital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edital_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Edital',
                'verbose_name_plural': 'Históricos de Editais',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='EditalFavorite',
        ),
        migrations.AddIndex(
            model_name='editalhistory',
            index=models.Index(fields=['-timestamp'], name='editais_edi_timesta_9bf6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='editalhistory',
            index=models.Index(fields=['edital', '-timestamp'], name='editais_edi_edital__5c9f55_idx'),
        ),
    ]
