# Generated by Django 5.2.7 on 2025-11-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0007_editalhistory_delete_editalfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editalhistory',
            name='edital_titulo',
            field=models.CharField(blank=True, help_text='Título do edital (preservado quando edital é deletado)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editalhistory',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='editais.edital'),
        ),
    ]
