# Generated by Django 5.2.7 on 2025-11-13 19:23
#
# This migration improves EditalHistory to handle deleted editais gracefully.
# When an edital is deleted, we want to preserve the history record, so:
# - The edital ForeignKey is changed to SET_NULL (preserves history when edital deleted)
# - The edital_titulo field is added to preserve the title even after deletion
# This ensures historical records remain accessible and meaningful even if the
# original edital no longer exists.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0007_editalhistory_delete_editalfavorite_and_more'),
    ]

    operations = [
        # Preserve edital title in history even after edital is deleted
        migrations.AddField(
            model_name='editalhistory',
            name='edital_titulo',
            field=models.CharField(blank=True, help_text='Título do edital (preservado quando edital é deletado)', max_length=500, null=True),
        ),
        # Allow history to persist even when edital is deleted (SET_NULL)
        migrations.AlterField(
            model_name='editalhistory',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='editais.edital'),
        ),
    ]
