# Generated by Django 5.2.7 on 2025-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0008_editalhistory_edital_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editalvalor',
            options={'verbose_name': 'Valor do Edital', 'verbose_name_plural': 'Valores dos Editais'},
        ),
        migrations.AlterField(
            model_name='editalvalor',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real Brasileiro (R$)'), ('USD', 'Dólar Americano (US$)'), ('EUR', 'Euro (€)')], default='BRL', help_text='Moeda do valor total', max_length=10),
        ),
        migrations.AddIndex(
            model_name='cronograma',
            index=models.Index(fields=['edital', 'data_inicio'], name='idx_cronograma_edital_data'),
        ),
        migrations.AddIndex(
            model_name='cronograma',
            index=models.Index(fields=['data_inicio'], name='idx_cronograma_data_inicio'),
        ),
        migrations.AddIndex(
            model_name='editalvalor',
            index=models.Index(fields=['edital', 'moeda'], name='idx_edital_moeda'),
        ),
    ]
