# Generated by Django 5.2.7 on 2025-11-25 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0009_improve_database_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('status', models.CharField(choices=[('em_avaliacao', 'Em Avaliação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status')),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Nota/score do projeto (opcional)', max_digits=5, null=True, verbose_name='Nota')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='editais.edital', verbose_name='Edital')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_submetidos', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-submitted_on'],
                'indexes': [models.Index(fields=['-submitted_on'], name='idx_project_submitted'), models.Index(fields=['status'], name='idx_project_status'), models.Index(fields=['edital', 'status'], name='idx_project_edital_status'), models.Index(fields=['proponente'], name='idx_project_proponente')],
            },
        ),
    ]
