# Generated by Django 5.2.7 on 2025-12-02 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0011_update_project_to_startup_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('agtech', 'AgTech'), ('biotech', 'BioTech'), ('iot', 'IoT & Hardware'), ('edtech', 'EdTech'), ('other', 'Outro')], default='other', help_text='Categoria da startup', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da startup e sua solução', null=True, verbose_name='Descrição'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='idx_project_category'),
        ),
    ]
