# Generated by Django 5.2.7 on 2025-12-02 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0012_add_startup_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da startup', null=True, upload_to='startups/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='idx_project_slug'),
        ),
    ]
