# Generated by Django 5.2.7 on 2025-12-03 01:23
#
# This migration updates the Project model to better reflect its new purpose as a Startup model:
# - Removes unused 'note' field
# - Adds 'contato' field for startup contact information
# - Updates related_name from 'projetos' to 'startups' to match new terminology
#
# IMPORTANT: This migration creates a related_name conflict - both edital and proponente
# ForeignKeys use 'startups' as their related_name. This conflict is fixed in migration 0024,
# where proponente.related_name is changed to 'startups_owned'.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0014_populate_project_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.AddField(
            model_name='project',
            name='contato',
            field=models.TextField(blank=True, help_text='Informações de contato da startup (email, telefone, website, etc.)', null=True, verbose_name='Contato'),
        ),
        # Update related_name to 'startups' to match new model purpose
        # NOTE: This creates a conflict with proponente.related_name (also 'startups')
        # The conflict is resolved in migration 0024
        migrations.AlterField(
            model_name='project',
            name='edital',
            field=models.ForeignKey(blank=True, help_text='Edital relacionado (opcional - startups podem não ter edital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='editais.edital', verbose_name='Edital'),
        ),
        # WARNING: This creates a related_name conflict with edital.related_name above
        # Both use 'startups', which will cause Django system check errors
        # Fixed in migration 0024 by changing this to 'startups_owned'
        migrations.AlterField(
            model_name='project',
            name='proponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
