# Generated by Django 5.2.7 on 2025-12-03 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0014_populate_project_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.AddField(
            model_name='project',
            name='contato',
            field=models.TextField(blank=True, help_text='Informações de contato da startup (email, telefone, website, etc.)', null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='project',
            name='edital',
            field=models.ForeignKey(blank=True, help_text='Edital relacionado (opcional - startups podem não ter edital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='editais.edital', verbose_name='Edital'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
