# Generated by Django 5.2.7 on 2025-12-03 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0016_allow_null_for_optional_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalvalor',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total (não pode ser negativo)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da startup (máximo 5MB, formatos: JPG, PNG, GIF)', null=True, upload_to='startups/logos/', verbose_name='Logo'),
        ),
    ]
