# Generated by Django 6.0 on 2025-12-07 15:23
#
# This migration performs two important operations:
#
# 1. TABLE RENAME: Renames editais_project to editais_startup
#    - Reflects the model's new purpose as a Startup model (changed in 0011)
#    - Uses SeparateDatabaseAndState to safely rename the table at the database level
#    - Handles multiple database backends (SQLite, PostgreSQL, others)
#    - Preserves all existing data during the rename
#
# 2. HISTORICAL MODEL: Creates HistoricalEdital model for django-simple-history
#    - django-simple-history requires the historical model to exist in migrations
#    - This enables automatic change tracking for the Edital model
#    - The HistoricalEdital model is automatically managed by django-simple-history
#    - Provides audit trail and change history functionality

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models, connection


def rename_project_table_if_exists(apps, schema_editor):
    """
    Rename editais_project table to editais_startup if it exists.
    Handles the case where the table might not exist or is already renamed.
    """
    db_engine = connection.settings_dict['ENGINE']
    
    with connection.cursor() as cursor:
        if 'sqlite' in db_engine:
            # SQLite: Check if editais_project exists, then rename
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='editais_project'"
            )
            if cursor.fetchone():
                # Check if editais_startup already exists (shouldn't happen, but be safe)
                cursor.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name='editais_startup'"
                )
                if not cursor.fetchone():
                    # Table exists and target doesn't, rename it
                    cursor.execute("ALTER TABLE editais_project RENAME TO editais_startup")
        elif 'postgresql' in db_engine:
            # PostgreSQL: Check if editais_project exists and editais_startup doesn't
            cursor.execute(
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'editais_project')"
            )
            project_exists = cursor.fetchone()[0]
            if project_exists:
                cursor.execute(
                    "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'editais_startup')"
                )
                startup_exists = cursor.fetchone()[0]
                if not startup_exists:
                    cursor.execute("ALTER TABLE editais_project RENAME TO editais_startup")
        else:
            # For other databases, try the rename (may fail if table doesn't exist)
            try:
                cursor.execute("ALTER TABLE editais_project RENAME TO editais_startup")
            except Exception:
                # Table doesn't exist or already renamed, skip
                pass


def reverse_rename_project_table(apps, schema_editor):
    """
    Reverse: Rename editais_startup back to editais_project if it exists.
    """
    db_engine = connection.settings_dict['ENGINE']
    
    if 'sqlite' in db_engine:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='editais_startup'"
            )
            if cursor.fetchone():
                cursor.execute("ALTER TABLE editais_startup RENAME TO editais_project")
    elif 'postgresql' in db_engine:
        with connection.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE IF EXISTS editais_startup RENAME TO editais_project"
            )
    else:
        try:
            with connection.cursor() as cursor:
                cursor.execute("ALTER TABLE editais_startup RENAME TO editais_project")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0021_remove_editalhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState to safely rename table at database level
        # while updating Django's state separately. This prevents issues with
        # Django's migration system trying to recreate the table.
        migrations.SeparateDatabaseAndState(
            # Database operations: rename table if it exists
            database_operations=[
                migrations.RunPython(
                    rename_project_table_if_exists,
                    reverse_rename_project_table,
                ),
            ],
            # State operations: update Django's understanding of the table name
            state_operations=[
                migrations.AlterModelTable(
                    name='project',
                    table='editais_startup',
                ),
            ],
        ),
        # Create HistoricalEdital model required by django-simple-history
        # This model is automatically managed by the library and provides
        # change tracking functionality for the Edital model.
        migrations.CreateModel(
            name='HistoricalEdital',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_edital', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('entidade_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('fechado', 'Fechado'), ('programado', 'Programado')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('analise', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('etapas', models.TextField(blank=True, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('itens_financiaveis', models.TextField(blank=True, null=True)),
                ('criterios_elegibilidade', models.TextField(blank=True, null=True)),
                ('criterios_avaliacao', models.TextField(blank=True, null=True)),
                ('itens_essenciais_observacoes', models.TextField(blank=True, null=True)),
                ('detalhes_unirv', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical Edital',
                'verbose_name_plural': 'historical Editais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
