# Generated by Django 5.2.7 on 2025-12-07
#
# This migration changes the logo field from ImageField to FileField.
#
# REASON: ImageField in Django uses PIL/Pillow for image processing, which does not
# support SVG files. SVG (Scalable Vector Graphics) is a common format for logos
# as it provides scalability without quality loss. By changing to FileField, we
# can accept SVG files while still supporting traditional image formats (JPG, PNG, GIF).
#
# Note: File validation (size, format) is handled in the model's clean() method
# rather than at the field level, providing more flexibility for SVG support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0022_alter_project_table_historicaledital'),
    ]

    operations = [
        # Change from ImageField to FileField to support SVG logos
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(
                blank=True,
                help_text='Logo da startup (máximo 5MB, formatos: JPG, PNG, GIF, SVG)',
                null=True,
                upload_to='startups/logos/',
                verbose_name='Logo'
            ),
        ),
    ]

