# Generated by Django 5.2.7 on 2025-12-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0022_alter_project_table_historicaledital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(
                blank=True,
                help_text='Logo da startup (máximo 5MB, formatos: JPG, PNG, GIF, SVG)',
                null=True,
                upload_to='startups/logos/',
                verbose_name='Logo'
            ),
        ),
    ]

