# Generated by Django 6.0.1 on 2026-02-05 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0029_add_startup_new_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cronograma',
            name='cronograma_data_fim_after_data_inicio',
        ),
        migrations.RemoveConstraint(
            model_name='edital',
            name='edital_end_date_after_start_date',
        ),
        migrations.AlterField(
            model_name='startup',
            name='contato',
            field=models.TextField(blank=True, help_text='Informações de contato da startup (email, telefone, etc.)', null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('pre_incubacao', 'Pré-Incubação'), ('incubacao', 'Incubação'), ('graduada', 'Graduada'), ('suspensa', 'Suspensa')], default='pre_incubacao', help_text='Fase de maturidade (Ideação, MVP, Escala, Suspensa). Indicador simbólico, não avaliação de aprovação.', max_length=20, verbose_name='Fase'),
        ),
        migrations.AddConstraint(
            model_name='cronograma',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio')), ('data_fim__isnull', True), ('data_inicio__isnull', True), _connector='OR'), name='cronograma_data_fim_after_data_inicio'),
        ),
        migrations.AddConstraint(
            model_name='edital',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), ('start_date__isnull', True), _connector='OR'), name='edital_end_date_after_start_date'),
        ),
    ]
